defaults:
  - _self_
  - data: default
  - model: resnet18
  - train: default
  - inference: default
  - logger: mlflow

project:
  name: "uk_flowers"
  seed: 42
  device: "auto" # Options: "cuda", "mps", "cpu", "auto"
